# Generated by Django 4.2.17 on 2025-01-31 20:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=cloudinary.models.CloudinaryField(default='no_image.svg', max_length=255, verbose_name='image'),
        ),
    ]
